export const API_GET_SUBREDDIT_SUCCESS = "API_GET_SUBREDDIT_SUCCESS"
export const API_GET_SUBREDDIT_FAILURE = "API_GET_SUBREDDIT_FAILURE"

export const API_GET_ENTRY_SUCCESS = "API_GET_ENTRY_SUCCESS"
export const API_GET_ENTRY_FAILURE = "API_GET_ENTRY_FAILURE"

export const SET_LIMIT = "SET_LIMIT"
export const SET_PAGE = "SET_PAGE"